openapi: 3.0.3
info:
  title: API Specification
  description: クライアント-サーバー間のデータ通信仕様
  version: "0.4.0"
servers:
  - url: http://localhost:5000/v1
    description: Development server
paths:
  /inspection-sheets:
    get:
      tags:
        - inspection sheets
      summary: Get all inspection sheets.
      description: ""
      parameters: []
      responses:
        "200":
          description: A JSON array of InspectionSheet model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InspectionSheet"
        "500":
          description: システムエラー Internal Server Error
    post:
      tags:
        - inspection sheets
      summary: Create a new InspectionSheet model
      description: ""
      parameters: []
      requestBody:
        description: inspection sheet to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionSheet"
      responses:
        "201":
          description: Single InspectionSheet model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionSheet"
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "500":
          description: システムエラー Internal Server Error
  /inspection-sheets/{sheet_id}:
    get:
      tags:
        - inspection sheets
      summary: Get the specified inspection sheet.
      description: ""
      parameters:
        - name: sheet_id
          in: path
          description: inspection sheet ID to get
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A JSON InspectionSheet model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionSheet"
        "400":
          description: IDが設定されていない Bad Request
        "500":
          description: システムエラー Internal Server Error
    put:
      tags:
        - inspection sheets
      summary: Updates the InspectionSheet model.
      description: ""
      parameters:
        - name: sheet_id
          in: path
          description: inspection sheet ID to update
          required: true
          schema:
            type: integer
      requestBody:
        description: inspection sheet to update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionSheet"
      responses:
        "201":
          description: 正常系（非同期）Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionSheet"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
    delete:
      tags:
        - inspection sheets
      summary: Deletes the InspectionSheet model.
      description: ""
      parameters:
        - name: sheet_id
          in: path
          description: inspection sheet ID to delete
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
  /inspection-groups:
    get:
      tags:
        - inspection groups
      summary: Get all inspection groups.
      description: ""
      parameters: []
      responses:
        "200":
          description: A JSON array of InspectionGroup model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InspectionGroup"
                example:
                  - id: 1
                    description: group1
                  - id: 2
                    description: group2
        "500":
          description: システムエラー Internal Server Error
    post:
      tags:
        - inspection groups
      summary: Create a new InspectionGroup model
      description: ""
      parameters: []
      requestBody:
        description: inspection group to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionGroup"
            example:
              id: 0
              name: new group
      responses:
        "201":
          description: Single InspectionGroup model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionGroup"
              example:
                id: 1
                description: inspection group
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "500":
          description: システムエラー Internal Server Error
  /inspection-groups/{id}:
    get:
      tags:
        - inspection groups
      summary: Get InspectionGroup model by ID.
      description: ""
      parameters:
        - name: id
          in: path
          description: inspection group ID to get
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single InspectionGroup model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionGroup"
              example:
                id: 1
                description: group name
        "400":
          description: IDが設定されていない Bad Request
        "404":
          description: 対象リソースが存在しない Not Found
        "500":
          description: システムエラー Internal Server Error
    put:
      tags:
        - inspection groups
      summary: Updates the InspectionGroup model.
      description: ""
      parameters:
        - name: id
          in: path
          description: inspection group ID to update
          required: true
          schema:
            type: integer
      requestBody:
        description: inspection group to update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionGroup"
            example:
              id: 1
              description: group name
      responses:
        "201":
          description: 正常系（非同期）Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionGroup"
              example:
                id: 1
                description: updated group name
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
    delete:
      tags:
        - inspection groups
      summary: Deletes the InspectionGroup model.
      description: ""
      parameters:
        - name: id
          in: path
          description: inspection group ID to delete
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: The specified InspectionGroup model is deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionGroup"
              example:
                id: 1
                description: deleted group name
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
  /inspection-types:
    get:
      tags:
        - inspection types
      summary: Get all inspection types.
      description: ""
      parameters: []
      responses:
        "200":
          description: A JSON array of InspectionType model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InspectionType"
                example:
                  - id: 1
                    description: type1
                  - id: 2
                    description: type2
        "500":
          description: システムエラー Internal Server Error
    post:
      tags:
        - inspection types
      summary: Create a new InspectionType model
      description: ""
      parameters: []
      requestBody:
        description: inspection type to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionType"
            example:
              id: 0
              name: new type
      responses:
        "201":
          description: 正常系（非同期）Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionType"
              example:
                inspection_group_id: 1
                description: inspection type
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "500":
          description: システムエラー Internal Server Error
  /inspection-types/{id}:
    get:
      tags:
        - inspection types
      summary: Get InspectionType model by ID.
      description: ""
      parameters:
        - name: id
          in: path
          description: inspection type ID to get
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single InspectionType model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionType"
              example:
                id: 1
                description: type name
        "400":
          description: 無効なID Bad Request
        "404":
          description: 対象リソースが存在しない Not Found
        "500":
          description: システムエラー Internal Server Error
    put:
      tags:
        - inspection types
      summary: Updates the InspectionType model.
      description: ""
      parameters:
        - name: id
          in: path
          description: inspection type ID to update
          required: true
          schema:
            type: integer
      requestBody:
        description: inspection type to update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InspectionType"
            example:
              id: 1
              name: update type
      responses:
        "201":
          description: 正常系（非同期）Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionType"
              example:
                inspection_group_id: 1
                description: updated type name
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
    delete:
      tags:
        - inspection types
      summary: Deletes the InspectionType model.
      description: ""
      parameters:
        - name: id
          in: path
          description: inspection type ID to delete
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: The specified InspectionType model is deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InspectionType"
              example:
                id: 1
                description: type name
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
  /choice-templates:
    get:
      tags:
        - choice templates
      summary: Get all choice templates.
      description: Returns an array of ChoiceTemplate model
      parameters: []
      responses:
        "200":
          description: A JSON array of ChoiceTemplate model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChoiceTemplate"
                example:
                  - id: 1
                    choices:
                      - id: 1
                        description: OK
                      - id: 2
                        description: NG
                  - id: 2
                    choices:
                      - id: 3
                        description: Yes
                      - id: 4
                        description: No
                      - id: 5
                        description: Unknown
        "500":
          description: システムエラー Internal Server Error
    post:
      tags:
        - choice templates
      summary: Create a new ChoiceTemplate
      description: Create a new ChoiceTemplate
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChoiceTemplate"
            example:
              id: 0
              choices:
                - id: 1
                  description: OK
                - id: 2
                  description: NG
      responses:
        "201":
          description: 正常系（同期）Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChoiceTemplate"
                example:
                  id: 1
                  choices:
                    - id: 1
                      description: OK
                    - id: 2
                      description: NG
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "500":
          description: システムエラー Internal Server Error
  /choice-templates/{id}:
    get:
      tags:
        - choice templates
      summary: Get choiceTemplate by ID.
      description: Returns a single ChoiceTemplate model
      parameters:
        - name: id
          in: path
          description: choice template ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single ChoiceTemplate model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/ChoiceTemplate"
                example:
                  id: 1
                  choices:
                    - id: 1
                      description: OK
                    - id: 2
                      description: NG
        "400":
          description: バリデーションエラー or 業務エラー Bad Request
        "404":
          description: 対象リソースが存在しない Not Found
        "500":
          description: システムエラー Internal Server Error
    put:
      tags:
        - choice templates
      summary: Updates a ChoiceTemplate
      description: ""
      parameters:
        - name: id
          in: path
          description: choice template ID
          required: true
          schema:
            type: integer
      requestBody:
        description: choice template to update
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChoiceTemplate"
            example:
              id: 1
              choices:
                - id: 1
                  description: OK
                - id: 2
                  description: NG
      responses:
        "201":
          description: 正常系（非同期）Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChoiceTemplate"
              example:
                id: 1
                choices:
                  - id: 1
                    description: OK
                  - id: 2
                    description: NG
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "ChoiceTemplate not found"
        "500":
          description: システムエラー Internal Server Error
    delete:
      tags:
        - choice templates
      summary: Deletes a ChoiceTemplate
      description: ""
      parameters:
        - name: id
          in: path
          description: choice template ID
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: The specified ChoiceTemplate model is deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChoiceTemplate"
              example:
                id: 1
                choices:
                  - id: 1
                    description: OK
                  - id: 2
                    description: NG
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "ChoiceTemplate not found"
        "500":
          description: システムエラー Internal Server Error
components:
  schemas:
    Choice:
      type: object
      required:
        - choice_id
        - order_index
        - description
      properties:
        choice_id:
          type: integer
          format: int64
        order_index:
          type: integer
          format: int64
        description:
          type: string
    ChoiceTemplate:
      type: object
      required:
        - id
        - choices
      properties:
        id:
          type: integer
          format: int64
        choices:
          type: array
          items:
            $ref: "#/components/schemas/Option"
    Equipment:
      required:
        - equipment_id
        - equipment_name
        - inspection_items
        - order_index
      type: object
      properties:
        equipment_id:
          type: integer
          format: int32
        order_index:
          type: integer
          format: int32
        equipment_name:
          type: string
        inspection_items:
          type: array
          items:
            $ref: '#/components/schemas/InspectionItem'
      additionalProperties: false
    InspectionGroup:
      required:
        - description
        - id
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
      additionalProperties: false
    InspectionItem:
      required:
        - choices
        - input_type
        - inspection_content
        - inspection_item_id
        - order_index
      type: object
      properties:
        inspection_item_id:
          type: integer
          format: int32
        order_index:
          type: integer
          format: int32
        inspection_content:
          type: string
        input_type:
          type: integer
          format: int32
        choices:
          type: array
          items:
            $ref: '#/components/schemas/Choice'
      additionalProperties: false
    InspectionSheet:
      required:
        - equipments
        - inspection_group_id
        - inspection_type_id
        - sheet_id
        - sheet_name
      type: object
      properties:
        sheet_id:
          type: integer
          format: int32
        sheet_name:
          type: string
        inspection_type_id:
          type: integer
          format: int32
        inspection_group_id:
          type: integer
          format: int32
        equipments:
          type: array
          items:
            $ref: '#/components/schemas/Equipment'
      additionalProperties: false
    InspectionType:
      required:
        - description
        - id
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
      additionalProperties: false
    Option:
      required:
        - description
        - option_id
        - order_index
      type: object
      properties:
        option_id:
          type: integer
          format: int32
        order_index:
          type: integer
          format: int32
        description:
          type: string
      additionalProperties: false
